/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Partner {
    id: bigint;
    bio: string;
    name: string;
    photoUrl: string;
    expertise: Array<string>;
}
export type Time = bigint;
export interface Contact {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface Notification {
    id: bigint;
    title: string;
    body: string;
    timestamp: Time;
    category: NotificationCategory;
}
export enum NotificationCategory {
    GST = "GST",
    Budget = "Budget",
    SEEPZ_SEZ = "SEEPZ_SEZ",
    Customs = "Customs",
    FinanceBill = "FinanceBill",
    IncomeTax = "IncomeTax",
    SEBI = "SEBI",
    FinanceMarket = "FinanceMarket"
}
export interface backendInterface {
    addNotification(title: string, body: string, category: NotificationCategory): Promise<bigint>;
    getAllContacts(): Promise<Array<Contact>>;
    getAllNotifications(): Promise<Array<Notification>>;
    getContact(id: bigint): Promise<Contact | null>;
    getContactCount(): Promise<bigint>;
    getNotification(id: bigint): Promise<Notification | null>;
    getNotificationsByCategory(category: NotificationCategory): Promise<Array<Notification>>;
    getPartners(): Promise<Array<Partner>>;
    submitContact(name: string, email: string, phone: string, message: string): Promise<bigint>;
}
import type { Contact as _Contact, Notification as _Notification, NotificationCategory as _NotificationCategory, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addNotification(arg0: string, arg1: string, arg2: NotificationCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, arg1, to_candid_NotificationCategory_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, arg1, to_candid_NotificationCategory_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return result;
        }
    }
    async getAllNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotifications();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotifications();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContact(arg0: bigint): Promise<Contact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactCount();
            return result;
        }
    }
    async getNotification(arg0: bigint): Promise<Notification | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotification(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotification(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationsByCategory(arg0: NotificationCategory): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsByCategory(to_candid_NotificationCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsByCategory(to_candid_NotificationCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartners(): Promise<Array<Partner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartners();
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_NotificationCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationCategory): NotificationCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contact]): Contact | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notification]): Notification | null {
    return value.length === 0 ? null : from_candid_Notification_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    body: string;
    timestamp: _Time;
    category: _NotificationCategory;
}): {
    id: bigint;
    title: string;
    body: string;
    timestamp: Time;
    category: NotificationCategory;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        timestamp: value.timestamp,
        category: from_candid_NotificationCategory_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    GST: null;
} | {
    Budget: null;
} | {
    SEEPZ_SEZ: null;
} | {
    Customs: null;
} | {
    FinanceBill: null;
} | {
    IncomeTax: null;
} | {
    SEBI: null;
} | {
    FinanceMarket: null;
}): NotificationCategory {
    return "GST" in value ? NotificationCategory.GST : "Budget" in value ? NotificationCategory.Budget : "SEEPZ_SEZ" in value ? NotificationCategory.SEEPZ_SEZ : "Customs" in value ? NotificationCategory.Customs : "FinanceBill" in value ? NotificationCategory.FinanceBill : "IncomeTax" in value ? NotificationCategory.IncomeTax : "SEBI" in value ? NotificationCategory.SEBI : "FinanceMarket" in value ? NotificationCategory.FinanceMarket : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n4(_uploadFile, _downloadFile, x));
}
function to_candid_NotificationCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationCategory): _NotificationCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationCategory): {
    GST: null;
} | {
    Budget: null;
} | {
    SEEPZ_SEZ: null;
} | {
    Customs: null;
} | {
    FinanceBill: null;
} | {
    IncomeTax: null;
} | {
    SEBI: null;
} | {
    FinanceMarket: null;
} {
    return value == NotificationCategory.GST ? {
        GST: null
    } : value == NotificationCategory.Budget ? {
        Budget: null
    } : value == NotificationCategory.SEEPZ_SEZ ? {
        SEEPZ_SEZ: null
    } : value == NotificationCategory.Customs ? {
        Customs: null
    } : value == NotificationCategory.FinanceBill ? {
        FinanceBill: null
    } : value == NotificationCategory.IncomeTax ? {
        IncomeTax: null
    } : value == NotificationCategory.SEBI ? {
        SEBI: null
    } : value == NotificationCategory.FinanceMarket ? {
        FinanceMarket: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
