/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NotificationCategory = IDL.Variant({
  'GST' : IDL.Null,
  'Budget' : IDL.Null,
  'SEEPZ_SEZ' : IDL.Null,
  'Customs' : IDL.Null,
  'FinanceBill' : IDL.Null,
  'IncomeTax' : IDL.Null,
  'SEBI' : IDL.Null,
  'FinanceMarket' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Contact = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : Time,
  'category' : NotificationCategory,
});
export const Partner = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'qualifications' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'specialization' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotification' : IDL.Func(
      [IDL.Text, IDL.Text, NotificationCategory],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([IDL.Nat], [IDL.Opt(Contact)], ['query']),
  'getContactCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getNotification' : IDL.Func([IDL.Nat], [IDL.Opt(Notification)], ['query']),
  'getNotificationsByCategory' : IDL.Func(
      [NotificationCategory],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NotificationCategory = IDL.Variant({
    'GST' : IDL.Null,
    'Budget' : IDL.Null,
    'SEEPZ_SEZ' : IDL.Null,
    'Customs' : IDL.Null,
    'FinanceBill' : IDL.Null,
    'IncomeTax' : IDL.Null,
    'SEBI' : IDL.Null,
    'FinanceMarket' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Contact = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : Time,
    'category' : NotificationCategory,
  });
  const Partner = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'qualifications' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'specialization' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotification' : IDL.Func(
        [IDL.Text, IDL.Text, NotificationCategory],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([IDL.Nat], [IDL.Opt(Contact)], ['query']),
    'getContactCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getNotification' : IDL.Func([IDL.Nat], [IDL.Opt(Notification)], ['query']),
    'getNotificationsByCategory' : IDL.Func(
        [NotificationCategory],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };