/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'timestamp' : Time,
  'category' : NotificationCategory,
}
export type NotificationCategory = { 'GST' : null } |
  { 'Budget' : null } |
  { 'SEEPZ_SEZ' : null } |
  { 'Customs' : null } |
  { 'FinanceBill' : null } |
  { 'IncomeTax' : null } |
  { 'SEBI' : null } |
  { 'FinanceMarket' : null };
export interface Partner {
  'id' : bigint,
  'name' : string,
  'designation' : string,
  'qualifications' : string,
  'experienceYears' : bigint,
  'specialization' : Array<string>,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNotification' : ActorMethod<
    [string, string, NotificationCategory],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContact' : ActorMethod<[bigint], [] | [Contact]>,
  'getContactCount' : ActorMethod<[], bigint>,
  'getNotification' : ActorMethod<[bigint], [] | [Notification]>,
  'getNotificationsByCategory' : ActorMethod<
    [NotificationCategory],
    Array<Notification>
  >,
  'getPartners' : ActorMethod<[], Array<Partner>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitContact' : ActorMethod<[string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];